### ISSUE TITLE
text-shadow problem

### ISSUE THREAD

**Issue by calidion** [jeremyramin/terminal-plus#124]
text-shadow makes it looks very uncomfortable in ubuntu

**Comment by jeremyramin** [comment]
No text-shadow applied here. Webkit font rendering is a bit messy in Atom. I will have to play with CSS values to fix the text-shadow.

Linking this with issue #116.

**Comment by calidion** [comment]
i solved this by adding the following snippets to my stylesheet config.

```css
atom-panel, .tool-panel {
  text-shadow: none;
}
```
