### ISSUE TITLE
Make "close all" icon more subtle

### ISSUE THREAD

**Issue by distantnative** [jeremyramin/terminal-plus#181]
The bright red is quite aggressive - would love to see a (maybe optional) grey version for that icon. Or to hide that icon at all as an option.

Goes together with #85 to embed terminal-plus more naturally into Atom.

**Comment by gaintsev** [comment]
+1. Also it may be worth a try to change the color of the tabs, they are very contrasting. You can try for example Google's material palette, something like this:

![b9bsfih](https://cloud.githubusercontent.com/assets/5312559/13059730/20c678fa-d44e-11e5-95a5-e6ef76230517.png)

**Comment by hnguyen94** [comment]
+ 1

**Comment by hnguyen94** [comment]
+1

**Comment by mateosss** [comment]
Agree with both.

**Comment by glentner** [comment]
I also would like a more subtle option for the close-all icon.

**Comment by bdtomlin** [comment]
Throw these in your styles.less and adjust the colors to whatever you want.

Click on the "Atom" menu and then on "Stylesheet..." if you don't know how to get to your styles.less :)

```less
.terminal-plus.status-bar .icon-x {
  color: #8b93a6;
}

.terminal-plus.status-bar .icon-terminal {
  color: #8b93a6;
}
```
