### ISSUE TITLE
Intercepted keys

### ISSUE THREAD

**Issue by tuvistavie** [jeremyramin/terminal-plus#60]
Hi,

I just started using this package and I like it a lot, thanks for the great work!

I have a question about what keys are intercepted and how.
I have the following key bindings:

```yaml
'.platform-linux':
  'alt-f14': 'terminal-plus:toggle'
  'ctrl-f13': 'core:focus-previous'
  'ctrl-f14': 'core:focus-next'
```

The `terminal-plus:toggle` works perfectly even when I'm focusing the terminal but
`core:focus-next` and `core:focus-previous` seem to be intercepted when I am focusing
the terminal which makes it difficult to rapidly switch between the editor and the terminal.

Am I missing something here or is this how the current implementation works?

Thank you.
