### ISSUE TITLE
Output is cut

### ISSUE THREAD

**Issue by miguelcarax** [jeremyramin/terminal-plus#7]
Well, hi again. I have a new issue, the output of the terminal it's out of terminal.

Edit: It happens with full screen too.

![captura de pantalla de 2015-09-11 12-00-17](https://cloud.githubusercontent.com/assets/9194709/9812325/df35d748-587c-11e5-9190-c61ed0c74458.png)

**Comment by jeremyramin** [comment]
@miguelcarax Did this happen after resizing Atom?

**Comment by miguelcarax** [comment]
yes

**Comment by jeremyramin** [comment]
@miguelcarax Did you enter ls and then resize? or resize then ls? Currently the terminal cuts off the end if you resize down.

**Comment by miguelcarax** [comment]
it's cut in any form.

**Comment by jeremyramin** [comment]
Resizing removes letters from the right side until I change it. If your ls looks like that after a resize then yes that is a problem. It is just that your terminal should be adjusting to the new size. Are you on the latest update?

**Comment by jeremyramin** [comment]
@miguelcarax I just realized but are you using a monospaced font? Terminals rely on that to have proper spacing.

**Comment by jeremyramin** [comment]
Has this issue been fixed for you?

**Comment by miguelcarax** [comment]
Sorry, i was without internet those days. The problem was the font yeah... i change to default and now works properly. 

Can be posible to have a Solarized Dark theme?

Sorry for the late answer.

**Comment by jeremyramin** [comment]
Miguel, you can specify your own theme by adding the following template to your Atom stylesheet:
```css
.terminal-plus .xterm {
  background-color: ;
  color: ;

  ::selection {
    background-color: ;
  }

  .terminal-cursor {
    background-color: ;
  }
}
```
Your Atom stylesheet can be opened by clicking `File > Open Your Stylesheet` from the menu at the top of Atom. This is CSS and expects a color name or hex color attribute.

Example:
```css
.terminal-plus .xterm {
  background-color: black; // Terminal background
  color: white; // Font Color

  ::selection {
    background-color: blue; // Selection color
  }

  .terminal-cursor {
    background-color: white; // Cursor color
  }
}
```
